#pragma once

#include "Organizm.h"
#include "Swiat.h"
#include "Zwierze.h"
#include "Roslina.h"
#include "zwierzeta/Wilk.h"
#include "Trawa.h"
#include "Mlecz.h"
#include "zwierzeta/Owca.h"
#include "Guarana.h"
#include "WilczeJagody.h"
#include "BarszczSosnowskiego.h"
#include "zwierzeta/Zolw.h"
#include "zwierzeta/Lis.h"
#include "zwierzeta/Antylopa.h"
#include "Czlowiek.h"