#pragma once

#include "Organizm.h"
#include "Swiat.h"
#include "Zwierze.h"
#include "Roslina.h"
#include "zwierzeta/Wilk.h"
#include "rosliny/Trawa.h"
#include "rosliny/Mlecz.h"
#include "zwierzeta/Owca.h"
#include "rosliny/Guarana.h"
#include "rosliny/WilczeJagody.h"
#include "rosliny/BarszczSosnowskiego.h"
#include "zwierzeta/Zolw.h"
#include "zwierzeta/Lis.h"
#include "zwierzeta/Antylopa.h"
#include "Czlowiek.h"